apiVersion: apps/v1
kind: Deployment
metadata:
  name: pub-beerPurchaseService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pub-beerPurchaseService
  template:
    metadata:
      labels:
        app: pub-beerPurchaseService
    spec:
      containers:
        - image: datowl/beerPurchaseService
          name: pub-beerPurchaseService
          ports:
            - containerPort: 8085
              name: pub-beerPurchaseService
          env:
            - name: POSTGRES_ENDPOINT
              value: "jdbc:postgresql://192.168.0.101:5433/"
            - name: POSTGRES_PASSWORD
              value: "1322"
            - name: POSTGRES_USERNAME
              value: "postgres"